# Dependencies
markdown:         kramdown
# pygments:         true

# Permalinks
permalink:        pretty

# Setup
tagline:          'A Jekyll theme'
url:              https://tatianahbel.github.io/
# The subpath of your site, e.g. /blog, for generating urls
baseurl:          ""

author:
  name:           'Tatiana Hernandez'
  url:            https://twitter.com/tatiHdez

include:
  - _pages

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/TatianaHbel/personal

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
