# Dependencies
markdown:         kramdown
# pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            THEBELL
tagline:          'A Jekyll theme'
description:      This is the portfolio website of <span style="color:white">Tatiana Hernandez Bel</span>, teacher, designer and more things I don't remember
url:              https://tatianahbel.github.io/personal/
# The subpath of your site, e.g. /blog, for generating urls
baseurl:          "/personal"

author:
  name:           'Tatiana Hernandez'
  url:            https://twitter.com/tatiHdez

include:
  - _pages

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/TatianaHbel/personal

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
