# Dependencies
markdown:         kramdown
# pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Tatiana Hernandez
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://tatianahbel.github.io/personal/
# The subpath of your site, e.g. /blog, for generating urls
baseurl:          "/personal"

author:
  name:           'Tatiana Hernandez'
  url:            https://twitter.com/tatiHdez

include:
  - _pages

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/TatianaHbel/personal

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
